name: Quality Assurance

on:
  - push

jobs:
  test:
    env:
      PNPM_VERSION: '9.1.1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            cwd: ./
            args: [--frozen-lockfile]
          version: ${{ env.PNPM_VERSION }}

      - name: Check code style
        run: pnpm lint

      - name: Check library build
        run: pnpm build

      - name: Run tests
        run: pnpm test